name = "SLAM"
uuid = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
authors = ["jinlei <jinlei.phys@gmail.com>"]
version = "0.1.0"

[deps]
Blink = "ad839575-38b3-5650-b840-f874b8c74a25"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
Blink = "0.12.9"
FastGaussQuadrature = "0.5, 1"
JSON3 = "1.14.3"
LaTeXStrings = "1.4.0"
LinearAlgebra = "1.11.0"
Printf = "1.11.0"
SpecialFunctions = "2"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
